---
server:
  port: 8888

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot-k8s
    username: postgres
    password: postgres
    hikari:
      initialization-fail-timeout: 0
jpa:
  database-platform: org.hibernate.dialect.PostgresPlusDialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: create

---
spring:
  spring:
    profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: {POSTGRES_USER}
    password: {POSTGRES_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
jpa:
  database-platform: org.hibernate.dialect.PostgresPlusDialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: create
